runtime: python37
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index.html

- url: /(.*)
  static_files: templates/\1
  upload: templates/(.*)