runtime: python37

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index.html

- url: /(.*)
  static_files: templates/\1
  upload: templates/(.*)

- url: /(.*)
  static_files: templates/\1
  upload: templates/(.*)